dist: xenial

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=heatshrink2 setup.py test
  - make test-sdist
  - PYTHONPATH=. python scripts/benchmark.py
  - make fuzz FUZZ_TIME=1

after_success:
  - coveralls

before_deploy:
  - git clean -dfx

deploy:
  provider: pypi
  username: __token__
  password:
    secure: MqGW6fm5wZJI2LHLL5fYhqg7w1NwEs0uUxcRelppWy/UEv3HUf3dMa7+kVq1tUXlNfFNiMhKc+a9AdzP3RRwLYWkFlJi35PSWTMFysjog6DjY5ESGYZH5Km4Vy3NIze1Sk8aODoKSWPQ+n9YPGChnqErzErBGB1S2r9LJc0dpKbNXW3BFfKeiU6z4fx2CzH6mDLBQyOl5DlCN8crHOxcJkHq6Qukvt3T6+Psb/2ZH77SYgk7xo6w51CmFUj1N9tww3SEFRHLE6dvSAuPPv89UIy1VVl3GtUPYb9GfrU57/6QyCeoN9yvpMboU02lqRbj8iHQtS7Oa/Uhg3h2NpmYnQKA5L1biv9O22y0IsDaERzGB5gsZr9l6xPzI7o0GrxozNmQAYD0f9MVuM398IoZ65mOGVTi/Fx0J3PkgQhcRDkzkAjgI4QxYsAZd+LfzGZd9NpbbSlYSQKzWseZSvHXEWbKMK0wM+AbWRAFFEkEj5BDrHOIhEs+l4qz+QK11AGVhUhfjZK46KhZPD5Sd8pK//2cWjvMtK8qeaXJj5h1AgtvSFaF4381RPSnM7YeUpLO1HpeEsAW/pCYt5RVVPcky7khKhYLq5DEJqMOlMOcUNy8fL1UhQd6D/ARVyo/MYcyLmB1MeVuqhl3lzOZxfANPu1LeDEh36PamlQ9yoXudfk=
  edge: true
  skip_existing: true
  on:
    tags: true
